name: 'Create Blog Post Issue'
description: 'Creates an issue in GitHub for new blog posts.'
runs:
  using: 'node20'
  pre: 'npm install'
  main: 'create-issue.js'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication.'
    required: true
  POST_DATA:
    description: 'Data of the new blog posts to include in the issue.'
    required: true
outputs:
  issue-url:
    description: 'URL of the created issue.'
