---
name: 새로운 블로그 게시글 확인 테스트

on:
  workflow_dispatch:

jobs:
  check_blog_post_test: # action 메인 job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Install Node.js dependencies
      run: |
        cd ./.github/actions/create-blog-post-issue-test
        npm install

    - name: Check for new blog posts and update text files
      id: check_posts
      run: |
        output=$(python scrapper/main.py | sed ':a;N;$!ba;s/\n/::/g')
        if [ -z "$output" ]; then
          echo "새로운 게시글이 없습니다."
          echo "POST_DATA=" >> $GITHUB_ENV
        else
          echo "POST_DATA=$output" >> $GITHUB_ENV
        fi

    - name: Create GitHub Issue for new posts
      if: env.POST_DATA != ''
      uses: ./.github/actions/create-blog-post-issue-test
      with:
        POST_DATA: ${{ env.POST_DATA }}
...