name: Check New Blog Post

on:
  schedule:
    - cron: '0 12 * * *'  # 매일 대한민국 시간으로 아침 9시에 실행 (UTC 기준 오후 12시)
  workflow_dispatch:

jobs:
  check_blog_post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Check for new posts in Toss
      id: check_toss
      run: echo "::set-output name=link::$(python main.py --blog Toss)"

    - name: Check for new posts in Woowahan
      id: check_woowahan
      run: echo "::set-output name=link::$(python main.py --blog Woowahan)"

    - name: Create GitHub issue if new post is detected in Toss
      if: steps.check_toss.outputs.link != ''
      uses: actions/github-script@v5
      with:
        script: |
          const issueTitle = "New post detected in Toss!";
          const issueBody = `A new post has been detected in Toss. Check the link: ${{ steps.check_toss.outputs.link }}`;
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody
          });

    - name: Create GitHub issue if new post is detected in Woowahan
      if: steps.check_woowahan.outputs.link != ''
      uses: actions/github-script@v5
      with:
        script: |
          const issueTitle = "New post detected in Woowahan!";
          const issueBody = `A new post has been detected in Woowahan. Check the link: ${{ steps.check_woowahan.outputs.link }}`;
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: issueTitle,
            body: issueBody
          });
