name: 새로운 블로그 게시글 스크래핑

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  scrap_blog_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Set up Java
        uses: actions/setup-java@v4.2.2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v3.5.0
        with:
          gradle-version: '8.10'

      - name: Build with Gradle
        run: |
          echo $PATH
          ./gradlew clean build -x test
        working-directory: TechBlogNotificationsScrapper

      - name: Run JAR for Scrap posts
        run: java -jar build/libs/tech-blog-notifications-scrapper-0.0.1-SNAPSHOT.jar
        working-directory: TechBlogNotificationsScrapper
