name: 새로운 블로그 게시글 확인

on:
  schedule:
    - cron: '0 23 * * *' # 한국(UTC+9) 기준 오전 8시
  workflow_dispatch:

jobs:
  check_blog_post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Check for new blog posts and update text files
      id: check_posts
      run: |
        output=$(python main.py | sed ':a;N;$!ba;s/\n/::/g')
        if [ -z "$output" ]; then
          echo "새로운 게시글이 없습니다."
          echo "POST_DATA=" >> $GITHUB_ENV
        else
          echo "POST_DATA=$output" >> $GITHUB_ENV
        fi

    - name: Create GitHub Issue for new posts
      if: env.POST_DATA != ''
      uses: ./.github/actions/create-blog-post-issue
      with:
        GITHUB_TOKEN: ${{ secrets.TECHBLOG_ALARM_ISSUE_ACTION_TOKEN }}
        POST_DATA: ${{ env.POST_DATA }}
