name: 새로운 블로그 게시글 스크래핑

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  scrap_blog_post:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: '8.10'

      - name: Build with Gradle
        run: |
          echo $PATH
          ./gradlew build
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.AWS_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.AWS_DB_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.AWS_DB_PASSWORD }}
        working-directory: TechBlogNotificationsScrapper

      - name: Run JAR for Scrap posts
        run: java -jar build/libs/tech-blog-notifications-scrapper-0.0.1-SNAPSHOT.jar
        working-directory: TechBlogNotificationsScrapper