name: Check New Blog Post

on:
  schedule:
    - cron: '0 12 * * *'  # 매일 대한민국 시간으로 아침 9시에 실행 (UTC 기준 오후 12시)
  workflow_dispatch:

jobs:
  check_blog_post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script and set output
      id: run-script
      run: |
        output=$(python main.py | sed ':a;N;$!ba;s/\n/::/g')
        echo "NEW_POSTS=${output}" >> $GITHUB_ENV

    - name: Create GitHub Issue for new posts
      if: env.NEW_POSTS != ''
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.TECHBLOG_ALARM_ISSUE_ACTION_TOKEN }}
        script: |
          const currentDate = new Date();
          const formattedDate = `${currentDate.getFullYear()}.${currentDate.getMonth() + 1}.${currentDate.getDate()}`;
          const DATA = process.env.NEW_POSTS.split('::').join('\n');
          if (DATA) {
            const issueTitle = `새로운 블로그 게시글이 올라왔습니다! ${formattedDate}`;
            const issueBody = `## 새로운 블로그 게시글 목록\n\n${DATA.split('\n').map(link => `${link}`).join('\n')}`;
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });
          }
