---
name: 새로운 블로그 게시글 확인 테스트

on:
  workflow_dispatch:

jobs:
  check_blog_post_test: # action 메인 job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven
        run: |
          wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar -xvf apache-maven-3.9.6-bin.tar.gz
          mv apache-maven-3.9.6 /opt/
          echo "/opt/apache-maven-3.9.6/bin" >> $GITHUB_PATH

      - name: Install Node.js dependencies
        run: |
          cd ./.github/actions/create-blog-post-issue-test
          npm install

      #      - name: Install tree
      #        run: sudo apt-get update && sudo apt-get install tree
      #
      #      - name: Run tree to display structure
      #        run: tree
      
      - name: Build with Maven
        run: |
          echo $PATH
          mvn --batch-mode --update-snapshots verify

      - name: Check for new blog posts and update text files
        id: check_posts
        run: |
          mvn package
          output=$(java -jar target/teckblog-alarm-1.0-SNAPSHOT.jar)
          cd database
          cat Kakao_new.json
          echo "$output"
          if [ -z "$output" ]; then
            echo "새로운 게시글이 없습니다."
            echo "POST_DATA=" >> $GITHUB_ENV
          else
            echo "새로운 게시글이 있습니다."
            echo "POST_DATA=$output" >> $GITHUB_ENV
          fi

      - name: Create GitHub Issue for new posts
        if: env.POST_DATA != ''
        uses: ./.github/actions/create-blog-post-issue-test
        with:
          POST_DATA: ${{ env.POST_DATA }}
...