name: Check New Blog Post

on:
  schedule:
    - cron: '0 12 * * *'  # 매일 대한민국 시간으로 아침 9시에 실행 (UTC 기준 오후 12시)
  workflow_dispatch:

jobs:
  check_blog_post:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script
      run: python main.py
      id: run-script  # 이 id를 사용하여 이 단계의 출력을 참조합니다.
      continue-on-error: true

    - name: Create GitHub Issue for new posts
      if: steps.run-script.outputs.new-posts  # 새 게시물이 있을 때만 이 단계를 실행합니다.
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const links = `${{ steps.run-script.outputs.new-posts }}`;
          if (links) {
            const issueTitle = "New Blog Posts Detected!";
            const issueBody = `New posts have been detected:\n\n${links.split('\n').map(link => `- ${link}`).join('\n')}`;
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody
            });
          }

